<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Commerce.Modules.Audit</RootNamespace>
    <AssemblyName>Commerce.Modules.Audit</AssemblyName>
    <Description>Audit module registration.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Commerce.Audit.Infrastructure\Commerce.Audit.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Contracts\Commerce.Framework.Contracts.csproj" />
  </ItemGroup>
</Project>
