<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Commerce.Shipping.Contracts</RootNamespace>
    <AssemblyName>Commerce.Shipping.Contracts</AssemblyName>
    <Description>Shipping public contracts.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Commerce.Shipping.Domain\Commerce.Shipping.Domain.csproj" />
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Core\Commerce.Framework.Core.csproj" />
  </ItemGroup>

</Project>
