<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Commerce.Seo.Contracts</RootNamespace>
    <AssemblyName>Commerce.Seo.Contracts</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Commerce.Seo.Domain\Commerce.Seo.Domain.csproj" />
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Core\Commerce.Framework.Core.csproj" />
  </ItemGroup>
</Project>
