<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Commerce.Scheduling.Domain</RootNamespace>
    <AssemblyName>Commerce.Scheduling.Domain</AssemblyName>
    <Description>Background job domain model.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Core\Commerce.Framework.Core.csproj" />
    <ProjectReference Include="..\..\..\Framework\Scheduling\Commerce.Framework.Scheduling\Commerce.Framework.Scheduling.csproj" />
  </ItemGroup>
</Project>
