<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Commerce.Tax.Contracts</RootNamespace>
    <AssemblyName>Commerce.Tax.Contracts</AssemblyName>
    <Description>Tax public contracts.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Commerce.Tax.Domain\Commerce.Tax.Domain.csproj" />
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Core\Commerce.Framework.Core.csproj" />
  </ItemGroup>

</Project>
