<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Commerce.Shipping.Infrastructure</RootNamespace>
    <AssemblyName>Commerce.Shipping.Infrastructure</AssemblyName>
    <Description>Shipping infrastructure.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Commerce.Shipping.Application\Commerce.Shipping.Application.csproj" />
    <ProjectReference Include="..\Commerce.Shipping.Domain\Commerce.Shipping.Domain.csproj" />
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Contracts\Commerce.Framework.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Data\Commerce.Framework.Data.csproj" />
    <ProjectReference Include="..\..\Store\Commerce.Store.Domain\Commerce.Store.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
  </ItemGroup>

</Project>
