<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Commerce.Promotions.Contracts</RootNamespace>
    <AssemblyName>Commerce.Promotions.Contracts</AssemblyName>
    <Description>Promotions contracts.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Commerce.Promotions.Domain\Commerce.Promotions.Domain.csproj" />
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Core\Commerce.Framework.Core.csproj" />
  </ItemGroup>

</Project>
