<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Commerce.Tests.Unit.Integration</RootNamespace>
    <AssemblyName>Commerce.Tests.Unit.Integration</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Commerce\Framework\Commerce.Framework.Core\Commerce.Framework.Core.csproj" />
    <ProjectReference Include="..\..\..\src\Commerce\Modules\Integration\Commerce.Integration.Application\Commerce.Integration.Application.csproj" />
    <ProjectReference Include="..\..\..\src\Commerce\Modules\Integration\Commerce.Integration.Contracts\Commerce.Integration.Contracts.csproj" />
    <ProjectReference Include="..\..\..\src\Commerce\Modules\Integration\Commerce.Integration.Domain\Commerce.Integration.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
