<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Commerce.Downloads.Contracts</RootNamespace>
    <AssemblyName>Commerce.Downloads.Contracts</AssemblyName>
    <Description>Digital downloads contracts.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Commerce.Downloads.Domain\Commerce.Downloads.Domain.csproj" />
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Core\Commerce.Framework.Core.csproj" />
  </ItemGroup>

</Project>
