<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Commerce.Catalog.Application</RootNamespace>
    <AssemblyName>Commerce.Catalog.Application</AssemblyName>
    <Description>Catalog application services.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Commerce.Catalog.Contracts\Commerce.Catalog.Contracts.csproj" />
    <ProjectReference Include="..\Commerce.Catalog.Domain\Commerce.Catalog.Domain.csproj" />
    <ProjectReference Include="..\..\Media\Commerce.Media.Contracts\Commerce.Media.Contracts.csproj" />
    <ProjectReference Include="..\..\Inventory\Commerce.Inventory.Contracts\Commerce.Inventory.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Core\Commerce.Framework.Core.csproj" />
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Application\Commerce.Framework.Application.csproj" />
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Contracts\Commerce.Framework.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Domain\Commerce.Framework.Domain.csproj" />
  </ItemGroup>

</Project>
