<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Commerce.Modules.Analytics</RootNamespace>
    <AssemblyName>Commerce.Modules.Analytics</AssemblyName>
    <Description>Analytics module registration.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Commerce.Analytics.Infrastructure\Commerce.Analytics.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Contracts\Commerce.Framework.Contracts.csproj" />
  </ItemGroup>
</Project>
