<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Commerce.Notifications.Contracts</RootNamespace>
    <AssemblyName>Commerce.Notifications.Contracts</AssemblyName>
    <Description>Notification public contracts.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Commerce.Notifications.Domain\Commerce.Notifications.Domain.csproj" />
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Core\Commerce.Framework.Core.csproj" />
  </ItemGroup>
</Project>
