<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Commerce.Modules.Cache</RootNamespace>
    <AssemblyName>Commerce.Modules.Cache</AssemblyName>
    <Description>Cache module registration.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Commerce.Cache.Infrastructure\Commerce.Cache.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Contracts\Commerce.Framework.Contracts.csproj" />
  </ItemGroup>
</Project>
