<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Commerce.Pricing.Contracts</RootNamespace>
    <AssemblyName>Commerce.Pricing.Contracts</AssemblyName>
    <Description>Pricing and discount public contracts.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Commerce.Pricing.Domain\Commerce.Pricing.Domain.csproj" />
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Core\Commerce.Framework.Core.csproj" />
  </ItemGroup>

</Project>
