<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Commerce.Analytics.Contracts</RootNamespace>
    <AssemblyName>Commerce.Analytics.Contracts</AssemblyName>
    <Description>Analytics and reporting contracts.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Core\Commerce.Framework.Core.csproj" />
  </ItemGroup>
</Project>
