<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Commerce.Downloads.Domain</RootNamespace>
    <AssemblyName>Commerce.Downloads.Domain</AssemblyName>
    <Description>Digital downloads domain model.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Core\Commerce.Framework.Core.csproj" />
  </ItemGroup>

</Project>
