<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Commerce.Modules.Core</RootNamespace>
    <AssemblyName>Commerce.Modules.Core</AssemblyName>
    <Description>Core Commerce platform module.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Framework\Commerce.Framework.Contracts\Commerce.Framework.Contracts.csproj" />
  </ItemGroup>

</Project>
