<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Commerce.Cms.Contracts</RootNamespace>
    <AssemblyName>Commerce.Cms.Contracts</AssemblyName>
    <Description>CMS contracts.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Commerce.Cms.Domain\Commerce.Cms.Domain.csproj" />
    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Core\Commerce.Framework.Core.csproj" />
  </ItemGroup>
</Project>
