<Project Sdk="Microsoft.NET.Sdk">



  <PropertyGroup>

    <RootNamespace>Commerce.Payments.Contracts</RootNamespace>

    <AssemblyName>Commerce.Payments.Contracts</AssemblyName>

    <Description>Payments public contracts.</Description>

  </PropertyGroup>



  <ItemGroup>

    <ProjectReference Include="..\Commerce.Payments.Domain\Commerce.Payments.Domain.csproj" />

    <ProjectReference Include="..\..\..\Framework\Commerce.Framework.Core\Commerce.Framework.Core.csproj" />

  </ItemGroup>



</Project>

