<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Commerce.Tests.Unit.PaymentProviders</RootNamespace>
    <AssemblyName>Commerce.Tests.Unit.PaymentProviders</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Commerce\Plugins\Payment\Commerce.Plugin.Payment.ZarinPal\Commerce.Plugin.Payment.ZarinPal.csproj" />
    <ProjectReference Include="..\..\..\src\Commerce\Plugins\Payment\Commerce.Plugin.Payment.Stripe\Commerce.Plugin.Payment.Stripe.csproj" />
    <ProjectReference Include="..\..\..\src\Commerce\Modules\Payments\Commerce.Payments.Contracts\Commerce.Payments.Contracts.csproj" />
    <ProjectReference Include="..\..\..\src\Commerce\Modules\Payments\Commerce.Payments.Application\Commerce.Payments.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
