import { Injectable, signal } from '@angular/core';

export type SupportedLocale = 'en' | 'fa';
export type TextDirection = 'ltr' | 'rtl';

type TranslationDictionary = Record<string, string>;

const EN: TranslationDictionary = {
  'app.title': 'Commerce',
  'nav.dashboard': 'Dashboard',
  'nav.catalog': 'Catalog',
  'nav.products': 'Products',
  'nav.categories': 'Categories',
  'nav.attributes': 'Attributes',
  'nav.media': 'Media',
  'nav.customers': 'Customers',
  'nav.stores': 'Stores',
  'nav.languages': 'Languages',
  'nav.currencies': 'Currencies',
  'nav.settings': 'Settings',
  'nav.login': 'Login',
  'nav.logout': 'Logout',
  'nav.account': 'Account',
  'nav.addresses': 'Addresses',
  'nav.home': 'Home',
  'nav.shop': 'Shop',
  'nav.cart': 'Cart',
  'action.save': 'Save',
  'action.cancel': 'Cancel',
  'action.delete': 'Delete',
  'action.edit': 'Edit',
  'action.create': 'Create',
  'action.search': 'Search',
  'action.continue': 'Continue',
  'state.loading': 'Loading…',
  'state.empty': 'Nothing to show yet.',
  'state.error': 'Something went wrong.',
  'auth.login.title': 'Sign in',
  'auth.register.title': 'Create account',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.firstName': 'First name',
  'auth.lastName': 'Last name',
  'auth.phone': 'Phone',
  'catalog.products.title': 'Products',
  'catalog.categories.title': 'Categories',
  'catalog.attributes.title': 'Attributes',
  'customers.title': 'Customers',
  'unauthorized.title': 'Access denied',
  'unauthorized.message': 'You do not have permission to view this page.',
  'cart.title': 'Your cart',
  'cart.empty': 'Your cart is empty.',
  'cart.continueShopping': 'Continue shopping',
  'cart.quantity': 'Quantity',
  'cart.remove': 'Remove',
  'cart.clear': 'Clear cart',
  'cart.summary': 'Order summary',
  'cart.subtotal': 'Subtotal',
  'cart.checkoutUnavailable': 'Checkout (coming soon)',
  'cart.checkout': 'Proceed to checkout',
  'cart.addToCart': 'Add to cart',
  'cart.added': 'Added to cart',
  'cart.unavailable': 'This product is not available to purchase.',
  'checkout.title': 'Checkout',
  'checkout.steps': 'Checkout steps',
  'checkout.step.contact': 'Contact',
  'checkout.step.billing': 'Billing',
  'checkout.step.shipping': 'Shipping',
  'checkout.step.shippingMethod': 'Shipping method',
  'checkout.step.payment': 'Payment',
  'checkout.step.review': 'Review',
  'checkout.savedAddresses': 'Saved addresses',
  'checkout.country': 'Country',
  'checkout.city': 'City',
  'checkout.address': 'Address',
  'checkout.postalCode': 'Postal code',
  'checkout.useShippingAsBilling': 'Use shipping address as billing address',
  'checkout.noShipping': 'Shipping options are currently unavailable.',
  'checkout.noPayment': 'No payment methods are currently available.',
  'checkout.shipping': 'Shipping',
  'checkout.tax': 'Tax',
  'checkout.grandTotal': 'Grand total',
  'checkout.readyForOrder': 'Validate checkout',
  'checkout.readyMessage': 'Your checkout is ready for order creation.',
  'checkout.placeOrder': 'Place order',
  'nav.orders': 'Orders',
  'orders.myOrders': 'My orders',
  'orders.number': 'Order',
  'orders.status': 'Status',
  'orders.payment': 'Payment',
  'orders.fulfillment': 'Fulfillment',
  'orders.total': 'Total',
  'orders.date': 'Date',
  'orders.items': 'Items',
  'orders.cancelOrder': 'Cancel order',
  'orders.confirmation.title': 'Thank you for your order',
  'orders.confirmation.message': 'Your order has been placed successfully.',
  'action.view': 'View',
  'nav.inventory': 'Inventory',
  'inventory.title': 'Inventory',
  'inventory.detailTitle': 'Inventory item',
  'inventory.offerId': 'Offer',
  'inventory.onHand': 'On hand',
  'inventory.reserved': 'Reserved',
  'inventory.available': 'Available',
  'inventory.status': 'Status',
  'inventory.inStock': 'In stock',
  'inventory.outOfStock': 'Out of stock',
  'inventory.backorder': 'Backorder',
  'inventory.notTracked': 'Not tracked',
  'inventory.allStatuses': 'All statuses',
  'inventory.stockSummary': 'Stock summary',
  'inventory.adjustment': 'Stock adjustment',
  'inventory.quantityDelta': 'Quantity change',
  'inventory.movementType': 'Movement type',
  'inventory.reason': 'Reason',
  'inventory.applyAdjustment': 'Apply adjustment',
  'inventory.movementHistory': 'Movement history',
  'inventory.reservationHistory': 'Reservation history',
  'product.inStock': 'In stock',
  'product.outOfStock': 'Out of stock',
  'product.backorder': 'Available for backorder'
};

const FA: TranslationDictionary = {
  'app.title': 'فروشگاه',
  'nav.dashboard': 'داشبورد',
  'nav.catalog': 'کاتالوگ',
  'nav.products': 'محصولات',
  'nav.categories': 'دسته‌بندی‌ها',
  'nav.attributes': 'ویژگی‌ها',
  'nav.media': 'رسانه',
  'nav.customers': 'مشتریان',
  'nav.stores': 'فروشگاه‌ها',
  'nav.languages': 'زبان‌ها',
  'nav.currencies': 'ارزها',
  'nav.settings': 'تنظیمات',
  'nav.login': 'ورود',
  'nav.logout': 'خروج',
  'nav.account': 'حساب کاربری',
  'nav.addresses': 'آدرس‌ها',
  'nav.home': 'خانه',
  'nav.shop': 'فروشگاه',
  'nav.cart': 'سبد خرید',
  'action.save': 'ذخیره',
  'action.cancel': 'انصراف',
  'action.delete': 'حذف',
  'action.edit': 'ویرایش',
  'action.create': 'ایجاد',
  'action.search': 'جستجو',
  'action.continue': 'ادامه',
  'state.loading': 'در حال بارگذاری…',
  'state.empty': 'موردی برای نمایش وجود ندارد.',
  'state.error': 'خطایی رخ داد.',
  'auth.login.title': 'ورود',
  'auth.register.title': 'ثبت‌نام',
  'auth.email': 'ایمیل',
  'auth.password': 'رمز عبور',
  'auth.firstName': 'نام',
  'auth.lastName': 'نام خانوادگی',
  'auth.phone': 'تلفن',
  'catalog.products.title': 'محصولات',
  'catalog.categories.title': 'دسته‌بندی‌ها',
  'catalog.attributes.title': 'ویژگی‌ها',
  'customers.title': 'مشتریان',
  'unauthorized.title': 'دسترسی غیرمجاز',
  'unauthorized.message': 'شما مجوز مشاهده این صفحه را ندارید.',
  'cart.title': 'سبد خرید شما',
  'cart.empty': 'سبد خرید شما خالی است.',
  'cart.continueShopping': 'ادامه خرید',
  'cart.quantity': 'تعداد',
  'cart.remove': 'حذف',
  'cart.clear': 'خالی کردن سبد',
  'cart.summary': 'خلاصه سفارش',
  'cart.subtotal': 'جمع جزء',
  'cart.checkoutUnavailable': 'تسویه حساب (به‌زودی)',
  'cart.checkout': 'ادامه به تسویه حساب',
  'cart.addToCart': 'افزودن به سبد',
  'cart.added': 'به سبد اضافه شد',
  'cart.unavailable': 'این محصول قابل خرید نیست.',
  'checkout.title': 'تسویه حساب',
  'checkout.steps': 'مراحل تسویه حساب',
  'checkout.step.contact': 'تماس',
  'checkout.step.billing': 'صورتحساب',
  'checkout.step.shipping': 'ارسال',
  'checkout.step.shippingMethod': 'روش ارسال',
  'checkout.step.payment': 'پرداخت',
  'checkout.step.review': 'بازبینی',
  'checkout.savedAddresses': 'آدرس‌های ذخیره‌شده',
  'checkout.country': 'کشور',
  'checkout.city': 'شهر',
  'checkout.address': 'آدرس',
  'checkout.postalCode': 'کد پستی',
  'checkout.useShippingAsBilling': 'استفاده از آدرس ارسال به‌عنوان آدرس صورتحساب',
  'checkout.noShipping': 'گزینه‌های ارسال در حال حاضر در دسترس نیست.',
  'checkout.noPayment': 'روش پرداختی در حال حاضر در دسترس نیست.',
  'checkout.shipping': 'هزینه ارسال',
  'checkout.tax': 'مالیات',
  'checkout.grandTotal': 'مبلغ نهایی',
  'checkout.readyForOrder': 'اعتبارسنجی تسویه حساب',
  'checkout.readyMessage': 'تسویه حساب شما برای ایجاد سفارش آماده است.',
  'checkout.placeOrder': 'ثبت سفارش',
  'nav.orders': 'سفارش‌ها',
  'orders.myOrders': 'سفارش‌های من',
  'orders.number': 'سفارش',
  'orders.status': 'وضعیت',
  'orders.payment': 'پرداخت',
  'orders.fulfillment': 'ارسال',
  'orders.total': 'مبلغ',
  'orders.date': 'تاریخ',
  'orders.items': 'اقلام',
  'orders.cancelOrder': 'لغو سفارش',
  'orders.confirmation.title': 'از خرید شما سپاسگزاریم',
  'orders.confirmation.message': 'سفارش شما با موفقیت ثبت شد.',
  'action.view': 'مشاهده',
  'nav.inventory': 'موجودی',
  'inventory.title': 'موجودی',
  'inventory.detailTitle': 'قلم موجودی',
  'inventory.offerId': 'پیشنهاد',
  'inventory.onHand': 'موجودی فیزیکی',
  'inventory.reserved': 'رزرو شده',
  'inventory.available': 'قابل فروش',
  'inventory.status': 'وضعیت',
  'inventory.inStock': 'موجود',
  'inventory.outOfStock': 'ناموجود',
  'inventory.backorder': 'پیش‌سفارش',
  'inventory.notTracked': 'بدون ردیابی',
  'inventory.allStatuses': 'همه وضعیت‌ها',
  'inventory.stockSummary': 'خلاصه موجودی',
  'inventory.adjustment': 'تعدیل موجودی',
  'inventory.quantityDelta': 'تغییر تعداد',
  'inventory.movementType': 'نوع گردش',
  'inventory.reason': 'دلیل',
  'inventory.applyAdjustment': 'اعمال تعدیل',
  'inventory.movementHistory': 'تاریخچه گردش',
  'inventory.reservationHistory': 'تاریخچه رزرو',
  'product.inStock': 'موجود',
  'product.outOfStock': 'ناموجود',
  'product.backorder': 'قابل پیش‌سفارش'
};

const DICTIONARIES: Record<SupportedLocale, TranslationDictionary> = { en: EN, fa: FA };

@Injectable({ providedIn: 'root' })
export class LocalizationService {
  private readonly localeSignal = signal<SupportedLocale>('en');

  readonly locale = this.localeSignal.asReadonly();
  readonly direction = signal<TextDirection>('ltr');

  setLocale(locale: SupportedLocale): void {
    this.localeSignal.set(locale);
    const direction: TextDirection = locale === 'fa' ? 'rtl' : 'ltr';
    this.direction.set(direction);
    document.documentElement.lang = locale;
    document.documentElement.dir = direction;
  }

  translate(key: string, fallback?: string): string {
    const dictionary = DICTIONARIES[this.localeSignal()];
    return dictionary[key] ?? fallback ?? key;
  }
}
