import { Injectable, signal } from '@angular/core';

export type SupportedLocale = 'en' | 'fa';
export type TextDirection = 'ltr' | 'rtl';

type TranslationDictionary = Record<string, string>;

const EN: TranslationDictionary = {
  'app.title': 'Commerce',
  'nav.dashboard': 'Dashboard',
  'nav.catalog': 'Catalog',
  'nav.products': 'Products',
  'nav.categories': 'Categories',
  'nav.attributes': 'Attributes',
  'nav.media': 'Media',
  'nav.customers': 'Customers',
  'nav.stores': 'Stores',
  'nav.languages': 'Languages',
  'nav.currencies': 'Currencies',
  'nav.settings': 'Settings',
  'nav.login': 'Login',
  'nav.logout': 'Logout',
  'nav.account': 'Account',
  'nav.addresses': 'Addresses',
  'nav.home': 'Home',
  'nav.shop': 'Shop',
  'nav.cart': 'Cart',
  'action.save': 'Save',
  'action.cancel': 'Cancel',
  'action.delete': 'Delete',
  'action.edit': 'Edit',
  'action.create': 'Create',
  'action.configure': 'Configure',
  'action.search': 'Search',
  'action.continue': 'Continue',
  'state.loading': 'Loading…',
  'state.empty': 'Nothing to show yet.',
  'state.error': 'Something went wrong.',
  'auth.login.title': 'Sign in',
  'auth.register.title': 'Create account',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.firstName': 'First name',
  'auth.lastName': 'Last name',
  'auth.phone': 'Phone',
  'catalog.products.title': 'Products',
  'catalog.categories.title': 'Categories',
  'catalog.attributes.title': 'Attributes',
  'customers.title': 'Customers',
  'unauthorized.title': 'Access denied',
  'unauthorized.message': 'You do not have permission to view this page.',
  'cart.title': 'Your cart',
  'cart.empty': 'Your cart is empty.',
  'cart.continueShopping': 'Continue shopping',
  'cart.quantity': 'Quantity',
  'cart.remove': 'Remove',
  'cart.clear': 'Clear cart',
  'cart.summary': 'Order summary',
  'cart.subtotal': 'Subtotal',
  'cart.checkoutUnavailable': 'Checkout (coming soon)',
  'cart.checkout': 'Proceed to checkout',
  'cart.addToCart': 'Add to cart',
  'cart.added': 'Added to cart',
  'cart.unavailable': 'This product is not available to purchase.',
  'checkout.title': 'Checkout',
  'checkout.steps': 'Checkout steps',
  'checkout.step.contact': 'Contact',
  'checkout.step.billing': 'Billing',
  'checkout.step.shipping': 'Shipping',
  'checkout.step.shippingMethod': 'Shipping method',
  'checkout.step.payment': 'Payment',
  'checkout.step.review': 'Review',
  'checkout.savedAddresses': 'Saved addresses',
  'checkout.country': 'Country',
  'checkout.city': 'City',
  'checkout.address': 'Address',
  'checkout.postalCode': 'Postal code',
  'checkout.useShippingAsBilling': 'Use shipping address as billing address',
  'checkout.noShipping': 'Shipping options are currently unavailable.',
  'checkout.noPayment': 'No payment methods are currently available.',
  'checkout.shipping': 'Shipping',
  'checkout.tax': 'Tax',
  'checkout.productTax': 'Product tax',
  'checkout.shippingTax': 'Shipping tax',
  'checkout.pricesIncludeTax': 'Prices include tax',
  'checkout.grandTotal': 'Grand total',
  'checkout.readyForOrder': 'Validate checkout',
  'checkout.readyMessage': 'Your checkout is ready for order creation.',
  'checkout.placeOrder': 'Place order',
  'checkout.paymentProcessing': 'Processing payment…',
  'checkout.paymentFailed': 'Payment could not be completed.',
  'nav.orders': 'Orders',
  'orders.myOrders': 'My orders',
  'orders.number': 'Order',
  'orders.status': 'Status',
  'orders.payment': 'Payment',
  'orders.fulfillment': 'Fulfillment',
  'orders.total': 'Total',
  'orders.date': 'Date',
  'orders.items': 'Items',
  'orders.cancelOrder': 'Cancel order',
  'orders.confirmation.title': 'Thank you for your order',
  'orders.confirmation.message': 'Your order has been placed successfully.',
  'action.view': 'View',
  'action.close': 'Close',
  'action.export': 'Export',
  'action.import': 'Import',
  'action.reset': 'Reset',
  'action.apply': 'Apply',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.all': 'All',
  'common.status': 'Status',
  'common.actions': 'Actions',
  'common.published': 'Published',
  'common.draft': 'Draft',
  'common.visible': 'Visible',
  'common.hidden': 'Hidden',
  'admin.titleSuffix': 'Admin',
  'admin.menu': 'Menu',
  'admin.skipToContent': 'Skip to content',
  'admin.store': 'Store',
  'admin.language': 'Language',
  'admin.nav.overview': 'Overview',
  'admin.nav.catalog': 'Catalog',
  'admin.nav.sales': 'Sales',
  'admin.nav.inventory': 'Inventory',
  'admin.nav.pricing': 'Pricing',
  'admin.nav.marketing': 'Marketing',
  'admin.nav.content': 'Content',
  'admin.nav.operations': 'Operations',
  'admin.nav.system': 'System',
  'admin.table.actions': 'Actions',
  'admin.table.selectAll': 'Select all rows',
  'admin.table.selectRow': 'Select row',
  'admin.filters.reset': 'Reset filters',
  'admin.filters.searchPlaceholder': 'Search…',
  'admin.bulk.itemsSelected': 'items selected',
  'admin.bulk.delete': 'Delete selected',
  'admin.bulk.export': 'Export selected',
  'admin.pagination.previous': 'Previous',
  'admin.pagination.next': 'Next',
  'admin.pagination.page': 'Page',
  'admin.pagination.of': 'of',
  'admin.pagination.pageSize': 'Rows per page',
  'admin.settings.search': 'Search settings',
  'admin.settings.saved': 'Settings saved successfully.',
  'admin.settings.noResults': 'No settings match your search.',
  'admin.export.success': 'Export completed.',
  'admin.export.failed': 'Export failed.',
  'nav.customerSegments': 'Segments',
  'nav.loyaltyRewards': 'Loyalty rewards',
  'nav.affiliates': 'Affiliates',
  'nav.giftCards': 'Gift cards',
  'nav.wishlists': 'Wishlists',
  'nav.warehouses': 'Warehouses',
  'catalog.products.create': 'Create product',
  'catalog.products.deleteTitle': 'Delete product',
  'catalog.products.deleteMessage': 'Delete this product?',
  'catalog.products.export': 'Export products',
  'catalog.products.name': 'Name',
  'catalog.products.sku': 'SKU',
  'catalog.products.type': 'Type',
  'catalog.products.visibility': 'Visibility',
  'nav.inventory': 'Inventory',
  'inventory.title': 'Inventory',
  'inventory.detailTitle': 'Inventory item',
  'inventory.offerId': 'Offer',
  'inventory.onHand': 'On hand',
  'inventory.reserved': 'Reserved',
  'inventory.available': 'Available',
  'inventory.status': 'Status',
  'inventory.inStock': 'In stock',
  'inventory.outOfStock': 'Out of stock',
  'inventory.backorder': 'Backorder',
  'inventory.notTracked': 'Not tracked',
  'inventory.allStatuses': 'All statuses',
  'inventory.stockSummary': 'Stock summary',
  'inventory.adjustment': 'Stock adjustment',
  'inventory.quantityDelta': 'Quantity change',
  'inventory.movementType': 'Movement type',
  'inventory.reason': 'Reason',
  'inventory.applyAdjustment': 'Apply adjustment',
  'inventory.movementHistory': 'Movement history',
  'inventory.reservationHistory': 'Reservation history',
  'product.inStock': 'In stock',
  'product.outOfStock': 'Out of stock',
  'product.backorder': 'Available for backorder',
  'nav.discounts': 'Discounts',
  'nav.coupons': 'Coupons',
  'nav.customerGroups': 'Customer groups',
  'nav.cmsPages': 'CMS pages',
  'nav.cmsTopics': 'CMS topics',
  'nav.cmsMenus': 'CMS menus',
  'nav.cmsWidgets': 'CMS widgets',
  'nav.themes': 'Themes',
  'themes.title': 'Themes',
  'themes.configure': 'Configure theme',
  'themes.backToList': 'Back to themes',
  'themes.storeAssignment': 'Store assignment',
  'themes.branding': 'Branding settings',
  'themes.layouts': 'Layouts',
  'cms.pages': 'CMS pages',
  'cms.topics': 'CMS topics',
  'cms.menus': 'CMS menus',
  'cms.widgets': 'CMS widgets',
  'cms.widgetZones': 'Widget zones',
  'cms.widgetInstances': 'Widget instances',
  'cms.newPage': 'New page',
  'cms.editPage': 'Edit page',
  'cms.published': 'Published',
  'nav.taxSettings': 'Tax settings',
  'pricing.customerGroups': 'Customer groups',
  'tax.settings': 'Tax settings',
  'tax.enabled': 'Tax enabled',
  'tax.pricesIncludeTax': 'Prices include tax',
  'tax.shippingTaxable': 'Shipping taxable by default',
  'tax.defaultCategoryId': 'Default tax category ID',
  'nav.shippingMethods': 'Shipping methods',
  'nav.shippingZones': 'Shipping zones',
  'nav.shippingRates': 'Shipping rates',
  'nav.taxCategories': 'Tax categories',
  'nav.taxZones': 'Tax zones',
  'nav.taxRates': 'Tax rates',
  'nav.payments': 'Payments',
  'nav.paymentMethods': 'Payment methods',
  'nav.plugins': 'Plugins',
  'plugins.title': 'Plugins',
  'nav.reviews': 'Reviews',
  'nav.promotions': 'Promotions',
  'nav.seoSettings': 'SEO settings',
  'nav.seoUrlRecords': 'URL records',
  'reviews.title': 'Reviews',
  'reviews.wishlists': 'Wishlists',
  'reviews.product': 'Product',
  'reviews.customer': 'Customer',
  'reviews.rating': 'Rating',
  'reviews.titleField': 'Title',
  'reviews.content': 'Content',
  'reviews.status': 'Status',
  'reviews.verified': 'Verified purchase',
  'reviews.created': 'Created',
  'reviews.approve': 'Approve',
  'reviews.reject': 'Reject',
  'reviews.count': 'reviews',
  'reviews.empty': 'No reviews yet.',
  'reviews.submit': 'Submit review',
  'reviews.loginToReview': 'Sign in to write a review',
  'reviews.yourReview': 'Your review',
  'reviews.pendingNotice': 'awaiting moderation',
  'reviews.store': 'Store',
  'reviews.itemCount': 'Items',
  'reviews.lastAdded': 'Last added',
  'wishlist.title': 'My wishlist',
  'wishlist.add': 'Add to wishlist',
  'wishlist.added': 'Added to wishlist',
  'wishlist.remove': 'Remove',
  'wishlist.empty': 'Your wishlist is empty.',
  'wishlist.addedAt': 'Added',
  'wishlist.available': 'Available',
  'wishlist.unavailable': 'Unavailable',
  'plugins.name': 'Name',
  'plugins.systemName': 'System name',
  'plugins.version': 'Version',
  'plugins.status': 'Status',
  'plugins.installed': 'Installed',
  'plugins.enabled': 'Enabled',
  'plugins.author': 'Author',
  'plugins.assembly': 'Assembly',
  'plugins.directory': 'Directory',
  'plugins.minVersion': 'Minimum Commerce version',
  'plugins.installedAt': 'Installed at',
  'plugins.description': 'Description',
  'plugins.dependencies': 'Dependencies',
  'plugins.install': 'Install',
  'plugins.enable': 'Enable',
  'plugins.disable': 'Disable',
  'plugins.uninstall': 'Uninstall',
  'plugins.reload': 'Reload',
  'plugins.installPackage': 'Install package',
  'plugins.installTitle': 'Install plugin',
  'plugins.enableTitle': 'Enable plugin',
  'plugins.disableTitle': 'Disable plugin',
  'plugins.uninstallTitle': 'Uninstall plugin',
  'plugins.reloadTitle': 'Reload plugin',
  'plugins.restartNote': 'Enable/disable and service registration changes may require an application restart.',
  'plugins.uninstallRemoveData': 'Uninstall and remove data',
  'plugins.uninstallRemoveDataTitle': 'Uninstall and remove plugin data',
  'plugins.uninstallRemoveDataMessage': 'This will uninstall the plugin and remove its store configuration data. Continue?',
  'plugins.tab.overview': 'Overview',
  'plugins.tab.configuration': 'Configuration',
  'plugins.tab.permissions': 'Permissions',
  'plugins.tab.stores': 'Stores',
  'plugins.tab.migrations': 'Migrations',
  'plugins.noSettings': 'This plugin has no configurable settings.',
  'plugins.noPermissions': 'This plugin does not declare permissions.',
  'plugins.noStoreConfig': 'No store-specific configuration exists yet.',
  'plugins.noMigrations': 'This plugin has no migrations.',
  'plugins.store': 'Store',
  'plugins.disabled': 'Disabled',
  'plugins.migrationName': 'Migration',
  'plugins.migrationVersion': 'Version',
  'plugins.applied': 'Applied',
  'plugins.pending': 'Pending',
  'plugins.updatedAt': 'Updated at',
  'downloads.title': 'My downloads',
  'downloads.empty': 'You have no downloadable products yet.',
  'downloads.grantedAt': 'Granted',
  'downloads.expiresAt': 'Expires',
  'downloads.remaining': 'Remaining downloads',
  'pricing.active': 'Active',
  'pricing.inactive': 'Inactive',
  'pricing.activate': 'Activate',
  'pricing.deactivate': 'Deactivate',
  'pricing.discounts.title': 'Discounts',
  'pricing.discounts.create': 'Create discount',
  'pricing.discounts.name': 'Name',
  'pricing.discounts.systemName': 'System name',
  'pricing.discounts.description': 'Description',
  'pricing.discounts.type': 'Type',
  'pricing.discounts.percentage': 'Percentage',
  'pricing.discounts.fixedAmount': 'Fixed amount',
  'pricing.discounts.value': 'Value',
  'pricing.discounts.currency': 'Currency',
  'pricing.discounts.priority': 'Priority',
  'pricing.discounts.active': 'Active',
  'pricing.discounts.scope': 'Application scope',
  'pricing.discounts.scopeLine': 'Line item',
  'pricing.discounts.scopeCart': 'Cart',
  'pricing.discounts.stackingMode': 'Stacking mode',
  'pricing.discounts.nonStackable': 'Non-stackable',
  'pricing.discounts.stackable': 'Stackable',
  'pricing.discounts.customerEligibility': 'Customer eligibility',
  'pricing.discounts.eligibilityAll': 'All customers',
  'pricing.discounts.eligibilityAuthenticated': 'Authenticated only',
  'pricing.discounts.eligibilityGuest': 'Guests only',
  'pricing.discounts.eligibilitySpecific': 'Specific customer',
  'pricing.discounts.specificCustomerId': 'Customer ID',
  'pricing.discounts.minimumCartSubtotal': 'Minimum cart subtotal',
  'pricing.discounts.minimumQuantity': 'Minimum quantity',
  'pricing.discounts.maximumDiscountAmount': 'Maximum discount amount',
  'pricing.discounts.startsAt': 'Starts at',
  'pricing.discounts.endsAt': 'Ends at',
  'pricing.discounts.storeId': 'Store ID',
  'pricing.discounts.targets': 'Targets',
  'pricing.discounts.addTarget': 'Add target',
  'pricing.discounts.targetProduct': 'Product',
  'pricing.discounts.targetVariant': 'Variant',
  'pricing.discounts.targetOffer': 'Offer',
  'pricing.discounts.targetCategory': 'Category',
  'pricing.discounts.targetCart': 'Cart',
  'pricing.discounts.deleteTitle': 'Delete discount',
  'pricing.discounts.deleteMessage': 'Delete discount',
  'pricing.coupons.title': 'Coupons',
  'pricing.coupons.create': 'Create coupon',
  'pricing.coupons.code': 'Coupon code',
  'pricing.coupons.discount': 'Discount',
  'pricing.coupons.selectDiscount': 'Select a discount',
  'pricing.coupons.usageCount': 'Usage count',
  'pricing.coupons.limits': 'Global / per customer limit',
  'pricing.coupons.globalUsageLimit': 'Global usage limit',
  'pricing.coupons.perCustomerUsageLimit': 'Per-customer usage limit',
  'pricing.coupons.deleteTitle': 'Delete coupon',
  'pricing.coupons.deleteMessage': 'Delete coupon',
  'promotions.title': 'Promotions',
  'promotions.create': 'Create promotion',
  'promotions.name': 'Name',
  'promotions.systemName': 'System name',
  'promotions.description': 'Description',
  'promotions.priority': 'Priority',
  'promotions.combinationRule': 'Combination rule',
  'promotions.combinationGroup': 'Combination group',
  'promotions.usage': 'Usage',
  'promotions.active': 'Active',
  'promotions.storeId': 'Store ID',
  'promotions.globalUsageLimit': 'Global usage limit',
  'promotions.perCustomerUsageLimit': 'Per-customer usage limit',
  'promotions.requiresCoupon': 'Requires coupon code',
  'promotions.couponCode': 'Coupon code',
  'promotions.startsAt': 'Starts at',
  'promotions.endsAt': 'Ends at',
  'promotions.conditions': 'Conditions',
  'promotions.actions': 'Actions',
  'promotions.minCartSubtotal': 'Minimum cart subtotal',
  'promotions.discountPercent': 'Discount percent',
  'promotions.actionScope': 'Action scope',
  'promotions.deleteTitle': 'Delete promotion',
  'seo.title': 'SEO',
  'seo.settings': 'SEO settings',
  'seo.urlRecords': 'URL records',
  'seo.upsertUrlRecord': 'Add or update URL record',
  'seo.entityName': 'Entity name',
  'seo.entityId': 'Entity ID',
  'seo.slug': 'Slug',
  'seo.storeId': 'Store ID',
  'seo.active': 'Active',
  'seo.defaultMetaTitle': 'Default meta title',
  'seo.defaultMetaDescription': 'Default meta description',
  'seo.robotsTxt': 'Robots.txt',
  'seo.sitemapEnabled': 'Sitemap enabled',
  'seo.publicEndpoints': 'Public endpoints: /robots.txt and /sitemap.xml',
  'notifications.templates.title': 'Notification templates',
  'notifications.templates.create': 'Create template',
  'notifications.templates.systemName': 'System name',
  'notifications.templates.eventType': 'Event type',
  'notifications.templates.channel': 'Channel',
  'notifications.templates.subject': 'Subject',
  'notifications.templates.body': 'Body',
  'notifications.templates.variablesJson': 'Variables (JSON)',
  'notifications.templates.languageId': 'Language ID',
  'notifications.templates.storeId': 'Store ID',
  'notifications.templates.enabled': 'Enabled',
  'notifications.templates.deleteTitle': 'Delete template',
  'notifications.logs.title': 'Notification history',
  'notifications.logs.eventType': 'Event',
  'notifications.logs.recipient': 'Recipient',
  'notifications.logs.status': 'Status',
  'notifications.logs.attempts': 'Attempts',
  'notifications.logs.createdAt': 'Created',
  'notifications.logs.retry': 'Retry',
  'nav.notificationTemplates': 'Notification templates',
  'nav.notificationLogs': 'Notification history',
  'scheduling.jobs.title': 'Background jobs',
  'scheduling.jobs.type': 'Job type',
  'scheduling.jobs.status': 'Status',
  'scheduling.jobs.attempts': 'Attempts',
  'scheduling.jobs.nextExecution': 'Next execution',
  'scheduling.jobs.createdAt': 'Created',
  'scheduling.jobs.retry': 'Retry',
  'scheduling.recurring.title': 'Recurring schedules',
  'scheduling.recurring.key': 'Schedule key',
  'scheduling.recurring.interval': 'Interval',
  'scheduling.recurring.enabled': 'Enabled',
  'nav.backgroundJobs': 'Background jobs',
  'nav.recurringJobs': 'Recurring jobs',
  'shipping.inactive': 'Inactive',
  'shipping.yes': 'Yes',
  'shipping.no': 'No',
  'shipping.displayOrder': 'Display order',
  'shipping.storeId': 'Store ID',
  'shipping.methods.title': 'Shipping methods',
  'shipping.methods.create': 'Create shipping method',
  'shipping.methods.name': 'Name',
  'shipping.methods.systemName': 'System name',
  'shipping.methods.description': 'Description',
  'shipping.methods.provider': 'Provider',
  'shipping.methods.requiresAddress': 'Requires address',
  'shipping.methods.supportsTracking': 'Supports tracking',
  'shipping.methods.estimatedDeliveryMin': 'Estimated delivery (min days)',
  'shipping.methods.estimatedDeliveryMax': 'Estimated delivery (max days)',
  'shipping.methods.deleteTitle': 'Delete shipping method',
  'shipping.methods.deleteMessage': 'Delete shipping method',
  'shipping.zones.title': 'Shipping zones',
  'shipping.zones.create': 'Create shipping zone',
  'shipping.zones.name': 'Name',
  'shipping.zones.systemName': 'System name',
  'shipping.zones.isDefault': 'Default zone',
  'shipping.zones.countries': 'Countries',
  'shipping.zones.countriesHint': 'US, CA, IR (comma-separated)',
  'shipping.zones.states': 'States / provinces',
  'shipping.zones.statesHint': 'US:CA, US:NY (optional)',
  'shipping.zones.postalRules': 'Postal rules',
  'shipping.zones.countryCode': 'Country',
  'shipping.zones.postalFrom': 'Postal from',
  'shipping.zones.postalTo': 'Postal to',
  'shipping.zones.addPostalRule': 'Add postal rule',
  'shipping.zones.ruleExact': 'Exact match',
  'shipping.zones.rulePrefix': 'Prefix',
  'shipping.zones.ruleRange': 'Range',
  'shipping.zones.deleteTitle': 'Delete shipping zone',
  'shipping.zones.deleteMessage': 'Delete shipping zone',
  'shipping.rates.title': 'Shipping rates',
  'shipping.rates.create': 'Create shipping rate',
  'shipping.rates.edit': 'Edit shipping rate',
  'shipping.rates.method': 'Shipping method',
  'shipping.rates.zone': 'Zone',
  'shipping.rates.currency': 'Currency',
  'shipping.rates.rateType': 'Rate type',
  'shipping.rates.basePrice': 'Base price',
  'shipping.rates.pricePerWeightUnit': 'Price per weight unit',
  'shipping.rates.freeShippingThreshold': 'Free shipping threshold',
  'shipping.rates.minOrderSubtotal': 'Min order subtotal',
  'shipping.rates.maxOrderSubtotal': 'Max order subtotal',
  'shipping.rates.selectMethod': 'Select a method',
  'shipping.rates.anyZone': 'Any zone',
  'shipping.rates.typeFlat': 'Flat rate',
  'shipping.rates.typeWeightBased': 'Weight based',
  'shipping.rates.typeOrderSubtotalBased': 'Order subtotal based',
  'shipping.rates.typeQuantityBased': 'Quantity based',
  'shipping.rates.deleteTitle': 'Delete shipping rate',
  'shipping.rates.deleteMessage': 'Delete this shipping rate?',
  'tax.active': 'Active',
  'tax.inactive': 'Inactive',
  'tax.yes': 'Yes',
  'tax.no': 'No',
  'tax.displayOrder': 'Display order',
  'tax.storeId': 'Store ID',
  'tax.categories.title': 'Tax categories',
  'tax.categories.create': 'Create tax category',
  'tax.categories.name': 'Name',
  'tax.categories.systemName': 'System name',
  'tax.categories.description': 'Description',
  'tax.categories.isExempt': 'Tax exempt',
  'tax.categories.deleteTitle': 'Delete tax category',
  'tax.categories.deleteMessage': 'Delete tax category',
  'tax.zones.title': 'Tax zones',
  'tax.zones.create': 'Create tax zone',
  'tax.zones.name': 'Name',
  'tax.zones.systemName': 'System name',
  'tax.zones.isDefault': 'Default zone',
  'tax.zones.countries': 'Countries',
  'tax.zones.countriesHint': 'US, CA, IR (comma-separated)',
  'tax.zones.states': 'States / provinces',
  'tax.zones.statesHint': 'US:CA, US:NY (optional)',
  'tax.zones.postalRules': 'Postal rules',
  'tax.zones.countryCode': 'Country',
  'tax.zones.postalFrom': 'Postal from',
  'tax.zones.postalTo': 'Postal to',
  'tax.zones.addPostalRule': 'Add postal rule',
  'tax.zones.ruleExact': 'Exact match',
  'tax.zones.rulePrefix': 'Prefix',
  'tax.zones.ruleRange': 'Range',
  'tax.zones.deleteTitle': 'Delete tax zone',
  'tax.zones.deleteMessage': 'Delete tax zone',
  'tax.rates.title': 'Tax rates',
  'tax.rates.create': 'Create tax rate',
  'tax.rates.edit': 'Edit tax rate',
  'tax.rates.category': 'Tax category',
  'tax.rates.zone': 'Zone',
  'tax.rates.percentage': 'Percentage',
  'tax.rates.taxShipping': 'Tax shipping',
  'tax.rates.priority': 'Priority',
  'tax.rates.rateType': 'Rate type',
  'tax.rates.selectCategory': 'Select a category',
  'tax.rates.anyZone': 'Any zone',
  'tax.rates.typePercentage': 'Percentage',
  'tax.rates.typeFixed': 'Fixed amount',
  'tax.rates.deleteTitle': 'Delete tax rate',
  'tax.rates.deleteMessage': 'Delete this tax rate?',
  'payments.active': 'Active',
  'payments.inactive': 'Inactive',
  'payments.displayOrder': 'Display order',
  'payments.storeId': 'Store ID',
  'payments.title': 'Payments',
  'payments.detail': 'Payment',
  'payments.id': 'ID',
  'payments.orderId': 'Order ID',
  'payments.amount': 'Amount',
  'payments.status': 'Status',
  'payments.provider': 'Provider',
  'payments.date': 'Date',
  'payments.allStatuses': 'All statuses',
  'payments.refundedAmount': 'Refunded amount',
  'payments.providerPaymentId': 'Provider payment ID',
  'payments.transactions': 'Transactions',
  'payments.noTransactions': 'No transactions yet.',
  'payments.transactionType': 'Type',
  'payments.failure': 'Failure',
  'payments.refunds': 'Refunds',
  'payments.reason': 'Reason',
  'payments.capture': 'Capture',
  'payments.void': 'Void',
  'payments.refund': 'Refund',
  'payments.captureConfirmTitle': 'Capture payment',
  'payments.captureConfirmMessage': 'Capture this authorized payment?',
  'payments.voidConfirmTitle': 'Void payment',
  'payments.voidConfirmMessage': 'Void this payment?',
  'payments.refundConfirmTitle': 'Refund payment',
  'payments.refundConfirmMessage': 'Issue a full refund for this payment?',
  'payments.methods.title': 'Payment methods',
  'payments.methods.create': 'Create payment method',
  'payments.methods.name': 'Name',
  'payments.methods.displayName': 'Display name',
  'payments.methods.systemName': 'System name',
  'payments.methods.provider': 'Provider',
  'payments.methods.requiresRedirect': 'Requires redirect',
  'payments.methods.supportsGuest': 'Supports guest checkout',
  'payments.methods.supportsFreeOrders': 'Supports free orders',
  'payments.methods.configurationJson': 'Configuration (JSON)',
  'payments.methods.deleteTitle': 'Delete payment method',
  'payments.methods.deleteMessage': 'Delete payment method',
  'payment.processing.title': 'Complete your payment',
  'payment.processing.message': 'Your order has been placed. Follow the instructions below to complete payment.',
  'payment.processing.instructions': 'Payment instructions',
  'payment.processing.continue': 'Continue to payment',
  'payment.success.title': 'Payment successful',
  'payment.success.message': 'Your payment was processed successfully.',
  'payment.success.viewOrder': 'View order details',
  'payment.failed.title': 'Payment failed',
  'payment.failed.message': 'We could not process your payment. Your order may still be pending payment.',
  'payment.failed.tryAgain': 'Return to checkout',
  'cart.couponCode': 'Coupon code',
  'cart.couponPlaceholder': 'Enter coupon code',
  'cart.applyCoupon': 'Apply',
  'cart.removeCoupon': 'Remove coupon',
  'cart.couponApplied': 'Coupon applied',
  'cart.discount': 'Discount',
  'cart.grandTotal': 'Total'
};

const FA: TranslationDictionary = {
  'app.title': 'فروشگاه',
  'nav.dashboard': 'داشبورد',
  'nav.catalog': 'کاتالوگ',
  'nav.products': 'محصولات',
  'nav.categories': 'دسته‌بندی‌ها',
  'nav.attributes': 'ویژگی‌ها',
  'nav.media': 'رسانه',
  'nav.customers': 'مشتریان',
  'nav.stores': 'فروشگاه‌ها',
  'nav.languages': 'زبان‌ها',
  'nav.currencies': 'ارزها',
  'nav.settings': 'تنظیمات',
  'nav.login': 'ورود',
  'nav.logout': 'خروج',
  'nav.account': 'حساب کاربری',
  'nav.addresses': 'آدرس‌ها',
  'nav.home': 'خانه',
  'nav.shop': 'فروشگاه',
  'nav.cart': 'سبد خرید',
  'action.save': 'ذخیره',
  'action.cancel': 'انصراف',
  'action.delete': 'حذف',
  'action.edit': 'ویرایش',
  'action.create': 'ایجاد',
  'action.configure': 'پیکربندی',
  'action.search': 'جستجو',
  'action.continue': 'ادامه',
  'state.loading': 'در حال بارگذاری…',
  'state.empty': 'موردی برای نمایش وجود ندارد.',
  'state.error': 'خطایی رخ داد.',
  'auth.login.title': 'ورود',
  'auth.register.title': 'ثبت‌نام',
  'auth.email': 'ایمیل',
  'auth.password': 'رمز عبور',
  'auth.firstName': 'نام',
  'auth.lastName': 'نام خانوادگی',
  'auth.phone': 'تلفن',
  'catalog.products.title': 'محصولات',
  'catalog.categories.title': 'دسته‌بندی‌ها',
  'catalog.attributes.title': 'ویژگی‌ها',
  'customers.title': 'مشتریان',
  'unauthorized.title': 'دسترسی غیرمجاز',
  'unauthorized.message': 'شما مجوز مشاهده این صفحه را ندارید.',
  'cart.title': 'سبد خرید شما',
  'cart.empty': 'سبد خرید شما خالی است.',
  'cart.continueShopping': 'ادامه خرید',
  'cart.quantity': 'تعداد',
  'cart.remove': 'حذف',
  'cart.clear': 'خالی کردن سبد',
  'cart.summary': 'خلاصه سفارش',
  'cart.subtotal': 'جمع جزء',
  'cart.checkoutUnavailable': 'تسویه حساب (به‌زودی)',
  'cart.checkout': 'ادامه به تسویه حساب',
  'cart.addToCart': 'افزودن به سبد',
  'cart.added': 'به سبد اضافه شد',
  'cart.unavailable': 'این محصول قابل خرید نیست.',
  'checkout.title': 'تسویه حساب',
  'checkout.steps': 'مراحل تسویه حساب',
  'checkout.step.contact': 'تماس',
  'checkout.step.billing': 'صورتحساب',
  'checkout.step.shipping': 'ارسال',
  'checkout.step.shippingMethod': 'روش ارسال',
  'checkout.step.payment': 'پرداخت',
  'checkout.step.review': 'بازبینی',
  'checkout.savedAddresses': 'آدرس‌های ذخیره‌شده',
  'checkout.country': 'کشور',
  'checkout.city': 'شهر',
  'checkout.address': 'آدرس',
  'checkout.postalCode': 'کد پستی',
  'checkout.useShippingAsBilling': 'استفاده از آدرس ارسال به‌عنوان آدرس صورتحساب',
  'checkout.noShipping': 'گزینه‌های ارسال در حال حاضر در دسترس نیست.',
  'checkout.noPayment': 'روش پرداختی در حال حاضر در دسترس نیست.',
  'checkout.shipping': 'هزینه ارسال',
  'checkout.tax': 'مالیات',
  'checkout.productTax': 'مالیات کالا',
  'checkout.shippingTax': 'مالیات ارسال',
  'checkout.pricesIncludeTax': 'قیمت‌ها شامل مالیات',
  'checkout.grandTotal': 'مبلغ نهایی',
  'checkout.readyForOrder': 'اعتبارسنجی تسویه حساب',
  'checkout.readyMessage': 'تسویه حساب شما برای ایجاد سفارش آماده است.',
  'checkout.placeOrder': 'ثبت سفارش',
  'checkout.paymentProcessing': 'در حال پردازش پرداخت…',
  'checkout.paymentFailed': 'پرداخت تکمیل نشد.',
  'nav.orders': 'سفارش‌ها',
  'orders.myOrders': 'سفارش‌های من',
  'orders.number': 'سفارش',
  'orders.status': 'وضعیت',
  'orders.payment': 'پرداخت',
  'orders.fulfillment': 'ارسال',
  'orders.total': 'مبلغ',
  'orders.date': 'تاریخ',
  'orders.items': 'اقلام',
  'orders.cancelOrder': 'لغو سفارش',
  'orders.confirmation.title': 'از خرید شما سپاسگزاریم',
  'orders.confirmation.message': 'سفارش شما با موفقیت ثبت شد.',
  'action.view': 'مشاهده',
  'action.close': 'بستن',
  'action.export': 'خروجی',
  'action.import': 'ورودی',
  'action.reset': 'بازنشانی',
  'action.apply': 'اعمال',
  'common.yes': 'بله',
  'common.no': 'خیر',
  'common.all': 'همه',
  'common.status': 'وضعیت',
  'common.actions': 'عملیات',
  'common.published': 'منتشر شده',
  'common.draft': 'پیش‌نویس',
  'common.visible': 'قابل مشاهده',
  'common.hidden': 'مخفی',
  'admin.titleSuffix': 'مدیریت',
  'admin.menu': 'منو',
  'admin.skipToContent': 'رفتن به محتوا',
  'admin.store': 'فروشگاه',
  'admin.language': 'زبان',
  'admin.nav.overview': 'نمای کلی',
  'admin.nav.catalog': 'کاتالوگ',
  'admin.nav.sales': 'فروش',
  'admin.nav.inventory': 'موجودی',
  'admin.nav.pricing': 'قیمت‌گذاری',
  'admin.nav.marketing': 'بازاریابی',
  'admin.nav.content': 'محتوا',
  'admin.nav.operations': 'عملیات',
  'admin.nav.system': 'سیستم',
  'admin.table.actions': 'عملیات',
  'admin.table.selectAll': 'انتخاب همه',
  'admin.table.selectRow': 'انتخاب ردیف',
  'admin.filters.reset': 'بازنشانی فیلترها',
  'admin.filters.searchPlaceholder': 'جستجو…',
  'admin.bulk.itemsSelected': 'مورد انتخاب شده',
  'admin.bulk.delete': 'حذف انتخاب‌شده‌ها',
  'admin.bulk.export': 'خروجی انتخاب‌شده‌ها',
  'admin.pagination.previous': 'قبلی',
  'admin.pagination.next': 'بعدی',
  'admin.pagination.page': 'صفحه',
  'admin.pagination.of': 'از',
  'admin.pagination.pageSize': 'تعداد در صفحه',
  'admin.settings.search': 'جستجوی تنظیمات',
  'admin.settings.saved': 'تنظیمات با موفقیت ذخیره شد.',
  'admin.settings.noResults': 'تنظیمی با این جستجو یافت نشد.',
  'admin.export.success': 'خروجی با موفقیت انجام شد.',
  'admin.export.failed': 'خروجی ناموفق بود.',
  'nav.customerSegments': 'بخش‌بندی مشتریان',
  'nav.loyaltyRewards': 'پاداش وفاداری',
  'nav.affiliates': 'همکاران فروش',
  'nav.giftCards': 'کارت هدیه',
  'nav.wishlists': 'لیست علاقه‌مندی',
  'nav.warehouses': 'انبارها',
  'catalog.products.create': 'ایجاد محصول',
  'catalog.products.deleteTitle': 'حذف محصول',
  'catalog.products.deleteMessage': 'این محصول حذف شود؟',
  'catalog.products.export': 'خروجی محصولات',
  'catalog.products.name': 'نام',
  'catalog.products.sku': 'کد کالا',
  'catalog.products.type': 'نوع',
  'catalog.products.visibility': 'نمایش',
  'nav.inventory': 'موجودی',
  'inventory.title': 'موجودی',
  'inventory.detailTitle': 'قلم موجودی',
  'inventory.offerId': 'پیشنهاد',
  'inventory.onHand': 'موجودی فیزیکی',
  'inventory.reserved': 'رزرو شده',
  'inventory.available': 'قابل فروش',
  'inventory.status': 'وضعیت',
  'inventory.inStock': 'موجود',
  'inventory.outOfStock': 'ناموجود',
  'inventory.backorder': 'پیش‌سفارش',
  'inventory.notTracked': 'بدون ردیابی',
  'inventory.allStatuses': 'همه وضعیت‌ها',
  'inventory.stockSummary': 'خلاصه موجودی',
  'inventory.adjustment': 'تعدیل موجودی',
  'inventory.quantityDelta': 'تغییر تعداد',
  'inventory.movementType': 'نوع گردش',
  'inventory.reason': 'دلیل',
  'inventory.applyAdjustment': 'اعمال تعدیل',
  'inventory.movementHistory': 'تاریخچه گردش',
  'inventory.reservationHistory': 'تاریخچه رزرو',
  'product.inStock': 'موجود',
  'product.outOfStock': 'ناموجود',
  'product.backorder': 'قابل پیش‌سفارش',
  'nav.discounts': 'تخفیف‌ها',
  'nav.coupons': 'کدهای تخفیف',
  'nav.customerGroups': 'گروه‌های مشتری',
  'nav.cmsPages': 'صفحات CMS',
  'nav.cmsTopics': 'موضوعات CMS',
  'nav.cmsMenus': 'منوهای CMS',
  'nav.cmsWidgets': 'ویجت‌های CMS',
  'nav.themes': 'قالب‌ها',
  'themes.title': 'قالب‌ها',
  'themes.configure': 'پیکربندی قالب',
  'themes.backToList': 'بازگشت به قالب‌ها',
  'themes.storeAssignment': 'اختصاص فروشگاه',
  'themes.branding': 'تنظیمات برند',
  'themes.layouts': 'چیدمان‌ها',
  'cms.pages': 'صفحات CMS',
  'cms.topics': 'موضوعات CMS',
  'cms.menus': 'منوهای CMS',
  'cms.widgets': 'ویجت‌های CMS',
  'cms.widgetZones': 'ناحیه‌های ویجت',
  'cms.widgetInstances': 'نمونه‌های ویجت',
  'cms.newPage': 'صفحه جدید',
  'cms.editPage': 'ویرایش صفحه',
  'cms.published': 'منتشر شده',
  'nav.taxSettings': 'تنظیمات مالیات',
  'pricing.customerGroups': 'گروه‌های مشتری',
  'tax.settings': 'تنظیمات مالیات',
  'tax.enabled': 'فعال بودن مالیات',
  'tax.pricesIncludeTax': 'قیمت‌ها شامل مالیات',
  'tax.shippingTaxable': 'مالیات پیش‌فرض روی ارسال',
  'tax.defaultCategoryId': 'شناسه دسته مالیاتی پیش‌فرض',
  'nav.shippingMethods': 'روش‌های ارسال',
  'nav.shippingZones': 'مناطق ارسال',
  'nav.shippingRates': 'نرخ‌های ارسال',
  'nav.taxCategories': 'دسته‌های مالیاتی',
  'nav.taxZones': 'مناطق مالیاتی',
  'nav.taxRates': 'نرخ‌های مالیاتی',
  'nav.payments': 'پرداخت‌ها',
  'nav.paymentMethods': 'روش‌های پرداخت',
  'nav.plugins': 'افزونه‌ها',
  'plugins.title': 'افزونه‌ها',
  'nav.reviews': 'نظرات',
  'nav.promotions': 'پروموشن‌ها',
  'nav.seoSettings': 'تنظیمات سئو',
  'nav.seoUrlRecords': 'رکوردهای URL',
  'reviews.title': 'نظرات',
  'reviews.wishlists': 'لیست علاقه‌مندی‌ها',
  'reviews.product': 'محصول',
  'reviews.customer': 'مشتری',
  'reviews.rating': 'امتیاز',
  'reviews.titleField': 'عنوان',
  'reviews.content': 'متن',
  'reviews.status': 'وضعیت',
  'reviews.verified': 'خرید تأییدشده',
  'reviews.created': 'ایجاد',
  'reviews.approve': 'تأیید',
  'reviews.reject': 'رد',
  'reviews.count': 'نظر',
  'reviews.empty': 'هنوز نظری ثبت نشده است.',
  'reviews.submit': 'ثبت نظر',
  'reviews.loginToReview': 'برای ثبت نظر وارد شوید',
  'reviews.yourReview': 'نظر شما',
  'reviews.pendingNotice': 'در انتظار بررسی',
  'reviews.store': 'فروشگاه',
  'reviews.itemCount': 'تعداد',
  'reviews.lastAdded': 'آخرین افزودن',
  'wishlist.title': 'لیست علاقه‌مندی من',
  'wishlist.add': 'افزودن به علاقه‌مندی',
  'wishlist.added': 'به علاقه‌مندی اضافه شد',
  'wishlist.remove': 'حذف',
  'wishlist.empty': 'لیست علاقه‌مندی شما خالی است.',
  'wishlist.addedAt': 'افزوده شده',
  'wishlist.available': 'موجود',
  'wishlist.unavailable': 'ناموجود',
  'plugins.name': 'نام',
  'plugins.systemName': 'نام سیستمی',
  'plugins.version': 'نسخه',
  'plugins.status': 'وضعیت',
  'plugins.installed': 'نصب‌شده',
  'plugins.enabled': 'فعال',
  'plugins.author': 'نویسنده',
  'plugins.assembly': 'Assembly',
  'plugins.directory': 'مسیر',
  'plugins.minVersion': 'حداقل نسخه Commerce',
  'plugins.installedAt': 'تاریخ نصب',
  'plugins.description': 'توضیحات',
  'plugins.dependencies': 'وابستگی‌ها',
  'plugins.install': 'نصب',
  'plugins.enable': 'فعال‌سازی',
  'plugins.disable': 'غیرفعال‌سازی',
  'plugins.uninstall': 'حذف',
  'plugins.reload': 'بارگذاری مجدد',
  'plugins.installPackage': 'نصب بسته',
  'plugins.installTitle': 'نصب افزونه',
  'plugins.enableTitle': 'فعال‌سازی افزونه',
  'plugins.disableTitle': 'غیرفعال‌سازی افزونه',
  'plugins.uninstallTitle': 'حذف افزونه',
  'plugins.reloadTitle': 'بارگذاری مجدد افزونه',
  'plugins.restartNote': 'تغییرات فعال/غیرفعال و ثبت سرویس ممکن است نیاز به راه‌اندازی مجدد برنامه داشته باشد.',
  'plugins.uninstallRemoveData': 'حذف همراه با داده',
  'plugins.uninstallRemoveDataTitle': 'حذف افزونه و داده‌های آن',
  'plugins.uninstallRemoveDataMessage': 'افزونه حذف می‌شود و پیکربندی فروشگاهی آن پاک می‌شود. ادامه می‌دهید؟',
  'plugins.tab.overview': 'نمای کلی',
  'plugins.tab.configuration': 'پیکربندی',
  'plugins.tab.permissions': 'مجوزها',
  'plugins.tab.stores': 'فروشگاه‌ها',
  'plugins.tab.migrations': 'مهاجرت‌ها',
  'plugins.noSettings': 'این افزونه تنظیمات قابل پیکربندی ندارد.',
  'plugins.noPermissions': 'این افزونه مجوزی تعریف نکرده است.',
  'plugins.noStoreConfig': 'هنوز پیکربندی فروشگاهی وجود ندارد.',
  'plugins.noMigrations': 'این افزونه مهاجرتی ندارد.',
  'plugins.store': 'فروشگاه',
  'plugins.disabled': 'غیرفعال',
  'plugins.migrationName': 'مهاجرت',
  'plugins.migrationVersion': 'نسخه',
  'plugins.applied': 'اعمال‌شده',
  'plugins.pending': 'در انتظار',
  'plugins.updatedAt': 'به‌روزرسانی',
  'downloads.title': 'دانلودهای من',
  'downloads.empty': 'هنوز محصول دانلودی ندارید.',
  'downloads.grantedAt': 'اعطا شده',
  'downloads.expiresAt': 'انقضا',
  'downloads.remaining': 'دانلود باقی‌مانده',
  'pricing.active': 'فعال',
  'pricing.inactive': 'غیرفعال',
  'pricing.activate': 'فعال‌سازی',
  'pricing.deactivate': 'غیرفعال‌سازی',
  'pricing.discounts.title': 'تخفیف‌ها',
  'pricing.discounts.create': 'ایجاد تخفیف',
  'pricing.discounts.name': 'نام',
  'pricing.discounts.systemName': 'نام سیستمی',
  'pricing.discounts.description': 'توضیحات',
  'pricing.discounts.type': 'نوع',
  'pricing.discounts.percentage': 'درصدی',
  'pricing.discounts.fixedAmount': 'مبلغ ثابت',
  'pricing.discounts.value': 'مقدار',
  'pricing.discounts.currency': 'ارز',
  'pricing.discounts.priority': 'اولویت',
  'pricing.discounts.active': 'فعال',
  'pricing.discounts.scope': 'محدوده اعمال',
  'pricing.discounts.scopeLine': 'قلم سفارش',
  'pricing.discounts.scopeCart': 'سبد خرید',
  'pricing.discounts.stackingMode': 'حالت تجمیع',
  'pricing.discounts.nonStackable': 'غیرقابل تجمیع',
  'pricing.discounts.stackable': 'قابل تجمیع',
  'pricing.discounts.customerEligibility': 'شرایط مشتری',
  'pricing.discounts.eligibilityAll': 'همه مشتریان',
  'pricing.discounts.eligibilityAuthenticated': 'فقط کاربران واردشده',
  'pricing.discounts.eligibilityGuest': 'فقط مهمان',
  'pricing.discounts.eligibilitySpecific': 'مشتری مشخص',
  'pricing.discounts.specificCustomerId': 'شناسه مشتری',
  'pricing.discounts.minimumCartSubtotal': 'حداقل جمع جزء سبد',
  'pricing.discounts.minimumQuantity': 'حداقل تعداد',
  'pricing.discounts.maximumDiscountAmount': 'حداکثر مبلغ تخفیف',
  'pricing.discounts.startsAt': 'شروع',
  'pricing.discounts.endsAt': 'پایان',
  'pricing.discounts.storeId': 'شناسه فروشگاه',
  'pricing.discounts.targets': 'اهداف',
  'pricing.discounts.addTarget': 'افزودن هدف',
  'pricing.discounts.targetProduct': 'محصول',
  'pricing.discounts.targetVariant': 'تنوع',
  'pricing.discounts.targetOffer': 'پیشنهاد',
  'pricing.discounts.targetCategory': 'دسته‌بندی',
  'pricing.discounts.targetCart': 'سبد خرید',
  'pricing.discounts.deleteTitle': 'حذف تخفیف',
  'pricing.discounts.deleteMessage': 'حذف تخفیف',
  'pricing.coupons.title': 'کدهای تخفیف',
  'pricing.coupons.create': 'ایجاد کد تخفیف',
  'pricing.coupons.code': 'کد تخفیف',
  'pricing.coupons.discount': 'تخفیف',
  'pricing.coupons.selectDiscount': 'انتخاب تخفیف',
  'pricing.coupons.usageCount': 'تعداد استفاده',
  'pricing.coupons.limits': 'محدودیت کلی / هر مشتری',
  'pricing.coupons.globalUsageLimit': 'محدودیت استفاده کلی',
  'pricing.coupons.perCustomerUsageLimit': 'محدودیت استفاده هر مشتری',
  'pricing.coupons.deleteTitle': 'حذف کد تخفیف',
  'pricing.coupons.deleteMessage': 'حذف کد تخفیف',
  'promotions.title': 'پروموشن‌ها',
  'promotions.create': 'ایجاد پروموشن',
  'promotions.name': 'نام',
  'promotions.systemName': 'نام سیستمی',
  'promotions.description': 'توضیحات',
  'promotions.priority': 'اولویت',
  'promotions.combinationRule': 'قانون ترکیب',
  'promotions.combinationGroup': 'گروه ترکیب',
  'promotions.usage': 'مصرف',
  'promotions.active': 'فعال',
  'promotions.storeId': 'شناسه فروشگاه',
  'promotions.globalUsageLimit': 'سقف مصرف کلی',
  'promotions.perCustomerUsageLimit': 'سقف مصرف هر مشتری',
  'promotions.requiresCoupon': 'نیاز به کد تخفیف',
  'promotions.couponCode': 'کد تخفیف',
  'promotions.startsAt': 'شروع',
  'promotions.endsAt': 'پایان',
  'promotions.conditions': 'شرایط',
  'promotions.actions': 'اقدامات',
  'promotions.minCartSubtotal': 'حداقل جمع جزء سبد',
  'promotions.discountPercent': 'درصد تخفیف',
  'promotions.actionScope': 'محدوده اقدام',
  'promotions.deleteTitle': 'حذف پروموشن',
  'seo.title': 'سئو',
  'seo.settings': 'تنظیمات سئو',
  'seo.urlRecords': 'رکوردهای URL',
  'seo.upsertUrlRecord': 'افزودن یا به‌روزرسانی رکورد URL',
  'seo.entityName': 'نام موجودیت',
  'seo.entityId': 'شناسه موجودیت',
  'seo.slug': 'اسلاگ',
  'seo.storeId': 'شناسه فروشگاه',
  'seo.active': 'فعال',
  'seo.defaultMetaTitle': 'عنوان متا پیش‌فرض',
  'seo.defaultMetaDescription': 'توضیح متا پیش‌فرض',
  'seo.robotsTxt': 'Robots.txt',
  'seo.sitemapEnabled': 'نقشه سایت فعال',
  'seo.publicEndpoints': 'مسیرهای عمومی: /robots.txt و /sitemap.xml',
  'notifications.templates.title': 'قالب‌های اعلان',
  'notifications.templates.create': 'ایجاد قالب',
  'notifications.templates.systemName': 'نام سیستمی',
  'notifications.templates.eventType': 'نوع رویداد',
  'notifications.templates.channel': 'کانال',
  'notifications.templates.subject': 'موضوع',
  'notifications.templates.body': 'متن',
  'notifications.templates.variablesJson': 'متغیرها (JSON)',
  'notifications.templates.languageId': 'شناسه زبان',
  'notifications.templates.storeId': 'شناسه فروشگاه',
  'notifications.templates.enabled': 'فعال',
  'notifications.templates.deleteTitle': 'حذف قالب',
  'notifications.logs.title': 'تاریخچه اعلان‌ها',
  'notifications.logs.eventType': 'رویداد',
  'notifications.logs.recipient': 'گیرنده',
  'notifications.logs.status': 'وضعیت',
  'notifications.logs.attempts': 'تلاش‌ها',
  'notifications.logs.createdAt': 'ایجاد',
  'notifications.logs.retry': 'تلاش مجدد',
  'nav.notificationTemplates': 'قالب‌های اعلان',
  'nav.notificationLogs': 'تاریخچه اعلان',
  'scheduling.jobs.title': 'کارهای پس‌زمینه',
  'scheduling.jobs.type': 'نوع کار',
  'scheduling.jobs.status': 'وضعیت',
  'scheduling.jobs.attempts': 'تلاش‌ها',
  'scheduling.jobs.nextExecution': 'اجرای بعدی',
  'scheduling.jobs.createdAt': 'ایجاد',
  'scheduling.jobs.retry': 'تلاش مجدد',
  'scheduling.recurring.title': 'زمان‌بندی‌های تکراری',
  'scheduling.recurring.key': 'کلید زمان‌بندی',
  'scheduling.recurring.interval': 'بازه',
  'scheduling.recurring.enabled': 'فعال',
  'nav.backgroundJobs': 'کارهای پس‌زمینه',
  'nav.recurringJobs': 'زمان‌بندی تکراری',
  'shipping.inactive': 'غیرفعال',
  'shipping.yes': 'بله',
  'shipping.no': 'خیر',
  'shipping.displayOrder': 'ترتیب نمایش',
  'shipping.storeId': 'شناسه فروشگاه',
  'shipping.methods.title': 'روش‌های ارسال',
  'shipping.methods.create': 'ایجاد روش ارسال',
  'shipping.methods.name': 'نام',
  'shipping.methods.systemName': 'نام سیستمی',
  'shipping.methods.description': 'توضیحات',
  'shipping.methods.provider': 'ارائه‌دهنده',
  'shipping.methods.requiresAddress': 'نیاز به آدرس',
  'shipping.methods.supportsTracking': 'پشتیبانی از رهگیری',
  'shipping.methods.estimatedDeliveryMin': 'حداقل روز تحویل',
  'shipping.methods.estimatedDeliveryMax': 'حداکثر روز تحویل',
  'shipping.methods.deleteTitle': 'حذف روش ارسال',
  'shipping.methods.deleteMessage': 'حذف روش ارسال',
  'shipping.zones.title': 'مناطق ارسال',
  'shipping.zones.create': 'ایجاد منطقه ارسال',
  'shipping.zones.name': 'نام',
  'shipping.zones.systemName': 'نام سیستمی',
  'shipping.zones.isDefault': 'منطقه پیش‌فرض',
  'shipping.zones.countries': 'کشورها',
  'shipping.zones.countriesHint': 'US, CA, IR (با کاما جدا کنید)',
  'shipping.zones.states': 'ایالت / استان',
  'shipping.zones.statesHint': 'US:CA, US:NY (اختیاری)',
  'shipping.zones.postalRules': 'قوانین کد پستی',
  'shipping.zones.countryCode': 'کشور',
  'shipping.zones.postalFrom': 'کد پستی از',
  'shipping.zones.postalTo': 'کد پستی تا',
  'shipping.zones.addPostalRule': 'افزودن قانون کد پستی',
  'shipping.zones.ruleExact': 'دقیق',
  'shipping.zones.rulePrefix': 'پیشوند',
  'shipping.zones.ruleRange': 'محدوده',
  'shipping.zones.deleteTitle': 'حذف منطقه ارسال',
  'shipping.zones.deleteMessage': 'حذف منطقه ارسال',
  'shipping.rates.title': 'نرخ‌های ارسال',
  'shipping.rates.create': 'ایجاد نرخ ارسال',
  'shipping.rates.edit': 'ویرایش نرخ ارسال',
  'shipping.rates.method': 'روش ارسال',
  'shipping.rates.zone': 'منطقه',
  'shipping.rates.currency': 'ارز',
  'shipping.rates.rateType': 'نوع نرخ',
  'shipping.rates.basePrice': 'قیمت پایه',
  'shipping.rates.pricePerWeightUnit': 'قیمت به ازای هر واحد وزن',
  'shipping.rates.freeShippingThreshold': 'آستانه ارسال رایگان',
  'shipping.rates.minOrderSubtotal': 'حداقل جمع جزء سفارش',
  'shipping.rates.maxOrderSubtotal': 'حداکثر جمع جزء سفارش',
  'shipping.rates.selectMethod': 'انتخاب روش',
  'shipping.rates.anyZone': 'هر منطقه',
  'shipping.rates.typeFlat': 'نرخ ثابت',
  'shipping.rates.typeWeightBased': 'بر اساس وزن',
  'shipping.rates.typeOrderSubtotalBased': 'بر اساس جمع جزء سفارش',
  'shipping.rates.typeQuantityBased': 'بر اساس تعداد',
  'shipping.rates.deleteTitle': 'حذف نرخ ارسال',
  'shipping.rates.deleteMessage': 'این نرخ ارسال حذف شود؟',
  'tax.active': 'فعال',
  'tax.inactive': 'غیرفعال',
  'tax.yes': 'بله',
  'tax.no': 'خیر',
  'tax.displayOrder': 'ترتیب نمایش',
  'tax.storeId': 'شناسه فروشگاه',
  'tax.categories.title': 'دسته‌های مالیاتی',
  'tax.categories.create': 'ایجاد دسته مالیاتی',
  'tax.categories.name': 'نام',
  'tax.categories.systemName': 'نام سیستمی',
  'tax.categories.description': 'توضیحات',
  'tax.categories.isExempt': 'معاف از مالیات',
  'tax.categories.deleteTitle': 'حذف دسته مالیاتی',
  'tax.categories.deleteMessage': 'حذف دسته مالیاتی',
  'tax.zones.title': 'مناطق مالیاتی',
  'tax.zones.create': 'ایجاد منطقه مالیاتی',
  'tax.zones.name': 'نام',
  'tax.zones.systemName': 'نام سیستمی',
  'tax.zones.isDefault': 'منطقه پیش‌فرض',
  'tax.zones.countries': 'کشورها',
  'tax.zones.countriesHint': 'US, CA, IR (با کاما جدا کنید)',
  'tax.zones.states': 'ایالت / استان',
  'tax.zones.statesHint': 'US:CA, US:NY (اختیاری)',
  'tax.zones.postalRules': 'قوانین کد پستی',
  'tax.zones.countryCode': 'کشور',
  'tax.zones.postalFrom': 'کد پستی از',
  'tax.zones.postalTo': 'کد پستی تا',
  'tax.zones.addPostalRule': 'افزودن قانون کد پستی',
  'tax.zones.ruleExact': 'تطابق دقیق',
  'tax.zones.rulePrefix': 'پیشوند',
  'tax.zones.ruleRange': 'محدوده',
  'tax.zones.deleteTitle': 'حذف منطقه مالیاتی',
  'tax.zones.deleteMessage': 'حذف منطقه مالیاتی',
  'tax.rates.title': 'نرخ‌های مالیاتی',
  'tax.rates.create': 'ایجاد نرخ مالیاتی',
  'tax.rates.edit': 'ویرایش نرخ مالیاتی',
  'tax.rates.category': 'دسته مالیاتی',
  'tax.rates.zone': 'منطقه',
  'tax.rates.percentage': 'درصد',
  'tax.rates.taxShipping': 'مالیات ارسال',
  'tax.rates.priority': 'اولویت',
  'tax.rates.rateType': 'نوع نرخ',
  'tax.rates.selectCategory': 'انتخاب دسته',
  'tax.rates.anyZone': 'هر منطقه',
  'tax.rates.typePercentage': 'درصدی',
  'tax.rates.typeFixed': 'مبلغ ثابت',
  'tax.rates.deleteTitle': 'حذف نرخ مالیاتی',
  'tax.rates.deleteMessage': 'این نرخ مالیاتی حذف شود؟',
  'payments.active': 'فعال',
  'payments.inactive': 'غیرفعال',
  'payments.displayOrder': 'ترتیب نمایش',
  'payments.storeId': 'شناسه فروشگاه',
  'payments.title': 'پرداخت‌ها',
  'payments.detail': 'پرداخت',
  'payments.id': 'شناسه',
  'payments.orderId': 'شناسه سفارش',
  'payments.amount': 'مبلغ',
  'payments.status': 'وضعیت',
  'payments.provider': 'ارائه‌دهنده',
  'payments.date': 'تاریخ',
  'payments.allStatuses': 'همه وضعیت‌ها',
  'payments.refundedAmount': 'مبلغ بازپرداخت‌شده',
  'payments.providerPaymentId': 'شناسه پرداخت ارائه‌دهنده',
  'payments.transactions': 'تراکنش‌ها',
  'payments.noTransactions': 'تراکنشی ثبت نشده است.',
  'payments.transactionType': 'نوع',
  'payments.failure': 'خطا',
  'payments.refunds': 'بازپرداخت‌ها',
  'payments.reason': 'دلیل',
  'payments.capture': 'دریافت',
  'payments.void': 'ابطال',
  'payments.refund': 'بازپرداخت',
  'payments.captureConfirmTitle': 'دریافت پرداخت',
  'payments.captureConfirmMessage': 'این پرداخت تأییدشده دریافت شود؟',
  'payments.voidConfirmTitle': 'ابطال پرداخت',
  'payments.voidConfirmMessage': 'این پرداخت ابطال شود؟',
  'payments.refundConfirmTitle': 'بازپرداخت',
  'payments.refundConfirmMessage': 'بازپرداخت کامل برای این پرداخت صادر شود؟',
  'payments.methods.title': 'روش‌های پرداخت',
  'payments.methods.create': 'ایجاد روش پرداخت',
  'payments.methods.name': 'نام',
  'payments.methods.displayName': 'نام نمایشی',
  'payments.methods.systemName': 'نام سیستمی',
  'payments.methods.provider': 'ارائه‌دهنده',
  'payments.methods.requiresRedirect': 'نیاز به هدایت',
  'payments.methods.supportsGuest': 'پشتیبانی از خرید مهمان',
  'payments.methods.supportsFreeOrders': 'پشتیبانی از سفارش رایگان',
  'payments.methods.configurationJson': 'پیکربندی (JSON)',
  'payments.methods.deleteTitle': 'حذف روش پرداخت',
  'payments.methods.deleteMessage': 'حذف روش پرداخت',
  'payment.processing.title': 'پرداخت خود را تکمیل کنید',
  'payment.processing.message': 'سفارش شما ثبت شد. برای تکمیل پرداخت دستورالعمل زیر را دنبال کنید.',
  'payment.processing.instructions': 'دستورالعمل پرداخت',
  'payment.processing.continue': 'ادامه به پرداخت',
  'payment.success.title': 'پرداخت موفق',
  'payment.success.message': 'پرداخت شما با موفقیت انجام شد.',
  'payment.success.viewOrder': 'مشاهده جزئیات سفارش',
  'payment.failed.title': 'پرداخت ناموفق',
  'payment.failed.message': 'پرداخت شما انجام نشد. سفارش ممکن است در انتظار پرداخت باشد.',
  'payment.failed.tryAgain': 'بازگشت به تسویه حساب',
  'cart.couponCode': 'کد تخفیف',
  'cart.couponPlaceholder': 'کد تخفیف را وارد کنید',
  'cart.applyCoupon': 'اعمال',
  'cart.removeCoupon': 'حذف کد تخفیف',
  'cart.couponApplied': 'کد تخفیف اعمال شد',
  'cart.discount': 'تخفیف',
  'cart.grandTotal': 'جمع کل'
};

const DICTIONARIES: Record<SupportedLocale, TranslationDictionary> = { en: EN, fa: FA };

const LOCALE_STORAGE_KEY = 'commerce.locale';

@Injectable({ providedIn: 'root' })
export class LocalizationService {
  private readonly localeSignal = signal<SupportedLocale>(this.readStoredLocale());

  readonly locale = this.localeSignal.asReadonly();
  readonly direction = signal<TextDirection>(this.localeSignal() === 'fa' ? 'rtl' : 'ltr');

  constructor() {
    this.applyDocumentLocale(this.localeSignal());
  }

  setLocale(locale: SupportedLocale, persist = false): void {
    this.localeSignal.set(locale);
    this.applyDocumentLocale(locale);
    if (persist) {
      localStorage.setItem(LOCALE_STORAGE_KEY, locale);
    }
  }

  translate(key: string, fallback?: string): string {
    const dictionary = DICTIONARIES[this.localeSignal()];
    return dictionary[key] ?? fallback ?? key;
  }

  private readStoredLocale(): SupportedLocale {
    const stored = localStorage.getItem(LOCALE_STORAGE_KEY);
    return stored === 'fa' || stored === 'en' ? stored : 'en';
  }

  private applyDocumentLocale(locale: SupportedLocale): void {
    const direction: TextDirection = locale === 'fa' ? 'rtl' : 'ltr';
    this.direction.set(direction);
    document.documentElement.lang = locale;
    document.documentElement.dir = direction;
  }
}
